#pragma once
#include <string>
#include "../ScriptHookV/natives.h"
class CBaseScaleform {
public:
	enum ScaleformVal {
		SCL_INVALID = -1,
	};
	CBaseScaleform(std::string scaleform);
	virtual void Draw() = 0;
	virtual void LitStrPush(std::string literalString);
	virtual void GXTStrPush(std::string gxtTablesStr);
	void IntegerPush(int i);
	void FloatPush(float f);
	void TextureStrPush(std::string str);
	void PlayerStrPush(std::string str);
	void BeginFunction(std::string funcName);
	void EndFunction();
	int EndFunctionWithReturn();
	bool isScaleformReadyToReturn(int retHandle);
	int GetScaleformValueInt(int retHandle);
	std::string GetScaleformValueStr(int retHandle);
	bool GetScaleformValueBool(int retHandle);
	int* GetScaleform() { return &m_Scaleform; }
protected:
	int m_Scaleform = SCL_INVALID;		//  The regular scaleform assignment goes to this one. 
	int m_ScaleformBG = SCL_INVALID;	//	
	int m_ScaleformFG = SCL_INVALID;	//	
	std::string m_ScfReq;
};
class CScaleform : public CBaseScaleform {
public:
	CScaleform(std::string scaleformName);
	/// <summary>
	/// Changing the scaleform on command I.E settings everything up. This is for regular users to use.
	/// All of the applied below take newScaleform because they allow
	/// </summary>
	/// <returns>
	/// Boolean to see if the operation was performed successfully.
	/// </returns>
	bool SET_SCALEFORM(std::string newScaleform);
	bool SET_SCALEFORMBG(std::string newScaleform);
	bool SET_SCALEFORMFG(std::string newScaleform);
private:
	const std::string frontEnd[26]		= {"AP_ICON","CREW_TAG_MOVIECLIP","FEED_AWARD","FEED_CREW_RANKUP","FEED_CREW_TAG","FEED_MESSAGE_TEXT","FEED_REPLAY","FEED_STATS	","FEED_TICKER","FEED_TOOLTIPS","FEED_UNLOCK","FEED_VERSUS","GAME_STREAM","GAME_STREAM_ENUMS","GTAV_ONLINE","INSTRUCTIONAL_BUTTONS","LANDING_PAGE","LOADINGSCREEN_NEWGAME","LOADINGSCREEN_STARTUP","MOUSE_EVENTS","MOUSE_POINTER","ONLINE_POLICIES","OPENING_CREDITS","PAUSE_MENU_BAR","PAUSE_MENU_CALIBRATION","PAUSE_MENU_CONFIGURATION_LIST","PAUSE_MENU_FREE_MODE","PAUSE_MENU_FREEMODE_DETAILS","PAUSE_MENU_HEADER","PAUSE_MENU_INSTRUCTIONAL_BUTTON","PAUSE_MENU_KEYMAP_CATEGORY","PAUSE_MENU_PAGES_KEYMAP","PAUSE_MENU_PAGES_SETTINGS","PAUSE_MENU_SETTINGS","PAUSE_MENU_SP_CONTENT","PAUSE_MENU_TEXT_LIST_DOUBLE","PAUSE_MENU_VERTICAL_LIST","PAUSE_MP_MENU_FRIENDS_LIST","PAUSE_MP_MENU_PLAYER_MODEL","POPUP_WARNING","ROCKSTAR_VERIFIED","RP_ICON","SOCIAL_CLUB2"};
	const std::string genericScl[318]	= {"AIRCRAFT_DIALS","AMBIENT_CLIP","AMMO_MASTER","APP_JOB_LIST","APP_MISSION_STATS_VIEW","APP_NUMBERPAD","APP_SECUROSERV_HACKING","APP_TODO_LIST","APP_TODO_VIEW","APP_TRACKIFY","ARCADE_BUSINESS_HUB","ARCADE_MANAGEMENT","ARENA_CAREER_WALL","ARENA_GUN_CAM","ARROW_WITH_EVENTS","ATM","AUDIO_CLIP","BANK_JOB_LOGIN","BIKER_BUSINESSES","BIKER_MISSION_WALL","BINOCULARS","BLIMP_TEXT","BOSS_JOB_LIST","BOSS_JOB_LIST_VIEW","BREAKING_NEWS","CALLSCREEN","CAMERA_GALLERY","CAMERA_SHUTTER","CASINO_HEIST_BOARD_FINALE","CASINO_HEIST_BOARD_PREP","CASINO_HEIST_BOARD_SETUP","CELLPHONE_ALERT_POPUP","CELLPHONE_BADGER","CELLPHONE_CUTSCENE","CELLPHONE_FACADE","CELLPHONE_IFRUIT","CELLPHONE_PROLOGUE	","CLIP_EDIT_TIMELINE	","CLIP_EDIT_TIMELINE_CLICK_REGION","CLUBHOUSE_NAME","COL_TYPE_BASIC_PAGE","COL_TYPE_IMG_PROJ_INFO	","COL_TYPE_IMG_TWELVE","COL_TYPE_LIST","COL_TYPE_LIST_HELP","COL_TYPE_LIST_LONG_AUDIO","COL_TYPE_LIST_PROJECT_SIZE","COL_TYPE_LIST_SCROLL","COL_TYPE_LIST_SCROLL_AUDIO","COL_TYPE_LOAD_PROJ_INFO","COL_TYPE_TEXT_PLACEMENT","COLOUR_SWITCHER","CONTACTLIST","CONTROLLER_TEST","COUNTDOWN","COVERT_OPS","CUSTOM_WARNING_SCREEN","DASHBOARD","DESKTOP_PC","DIAL_BANSHEE","DIAL_BOBCAT","DIAL_CAVALCADE","DIAL_COMET","DIAL_DUKES","DIAL_FACTION","DIAL_FELTZER","DIAL_FEROCI","DIAL_FUTO","DIAL_GENTAXI","DIAL_INFERNUS","DIAL_MAVERICK","DIAL_MOTORBIKE","DIAL_PEYOTE","DIAL_RACE","DIAL_RUINER","DIAL_SPEEDO","DIAL_SULTAN","DIAL_SUPERGT","DIAL_TAILGATER","DIAL_TRUCK","DIAL_TRUCKDIGI","DIAL_ZTYPE","DIGISCANNER","DIGITAL_CAMERA","DISRUPTION_LOGISTICS","DJ","DRILLING","DRONE_CAM","ECG_MONITOR","ECOMMERCE_STORE","EDITOR_SHUTTER","EMAIL_LIST","EMAIL_RESPONSE","EMAIL_VIEW	","GRID_LAYOUT","HACKER_TRUCK_DESKTOP","HACKING_PC	","HANGAR_CARGO","HEIST_AGENCY","HEIST_DOCKS","HEIST_ENDSCREEN""HEIST_FINALE","HEIST_JEWELLERY","HEIST_PALETO","HEIST2_CELEBRATION","HELI_CAM","HELP_TEXT","HELPTEXT","HOMEMENU","HOMEMENU_BADGER","HOMEMENU_FACADE","HOMEMENU_IFRUIT","HUD_AREA_NAME","HUD_AREA_VEHICLE_STREET_NAME","HUD_CASH","HUD_CASH_CHANGE","HUD_CASH_CHANGED","HUD_CHIPS","HUD_CHIPS_CHANGED","HUD_COMPONENT","HUD_DIRECTOR_MODE","HUD_DISTRICT_NAME","HUD_DRUGS_PURSE","HUD_FLOATING_HELP_TEXT","HUD_FLOATING_HELP_TEXT_1","HUD_FLOATING_HELP_TEXT_2","HUD_HELP_TEXT","HUD_HELP_TEXT_BIG","HUD_MISSION_PASSED_MESSAGE","HUD_MP_CASH","HUD_MP_INVENTORY","HUD_MP_MESSAGE","HUD_MULTIPLAYER_CHAT","HUD_PLAYER_SWITCH_ALERT","HUD_RADIO_STATIONS_WHEEL","HUD_RADIO_WHEEL","HUD_RETICLE","HUD_SAVING","HUD_STREET_NAME","HUD_SUBTITLE_TEXT","HUD_SUBTITLE_TEXT_BIG","HUD_VEHICLE_NAME","HUD_WANTED_STARS","HUD_WEAPON_ICON","HUD_WEAPON_WHEEL","HUD_WEAPON_WHEEL_STATS","IAA_HEIST_BOARD","IMPORT_EXPORT_WAREHOUSE","JOB_LIST","LESTER_HACK_PC","LETTER_SCRAPS","MARKER","MARKER_LEFT","MARKER_RIGHT","MESSAGE_LIST","MESSAGE_VIEW","MIDSIZED_MESSAGE","MISSION_COMPLETE","MISSION_QUIT","MISSION_REPEAT_LIST","MISSION_TARGET_COMPLETE","MORGUE_LAPTOP","MP_AWARD_BASE","MP_AWARD_FREEMODE","MP_BIG_MESSAGE_FREEMODE","MP_BOUNTY_BOARD","MP_CAR_STATS","MP_CELEBRATION","MP_CORONA_PLAYER_INFO","MP_CREW_TAG","MP_FREEMODE_CHECKPOINT_BASE","MP_FREEMODE_PLAYER_LIST","MP_GAMER_INFO","MP_MATCHMAKING_CARD","MP_MATCHMAKING_SELECTOR","MP_MATCHMAKING_VEHICLE_INFO","MP_MENU_GLARE","MP_MISSION_NAME_FREEMODE","MP_MM_CARD_FREEMODE","MP_NEXT_JOB_SELECTION","MP_PLAYER_CARD","MP_RANK_BAR","MP_RESULTS_PANEL","MP_SPECTATOR_CARD","MP_SPECTATOR_OVERLAY","MP_UNLOCKS_FREEMODE","MUGSHOT_BOARD","MULTIPLAYER_CHAT","NEW_EDITOR","NEW_HUD","NIGHTCLUB","OBSERVATORY_SCOPE","OPEN_WHEEL_HEALTH_INDICATOR","ORBITAL_CANNON_CAM","ORBITAL_CANNON_MAP","ORGANISATION_NAME","OVERVIEW_BACKGROUND","OVERVIEW_SCROLLER","PARTY_BUS","PAUSE_MENU_AWARDS","PAUSE_MENU_BODY_CONFIG_LIST","PAUSE_MENU_CHARACTER_CARD","PAUSE_MENU_CHARACTER_SELECT","PAUSE_MENU_CREW_COMPARISON_CARD","PAUSE_MENU_CREW_RANKS","PAUSE_MENU_CREWS_CARD","PAUSE_MENU_CREWS_LIST","PAUSE_MENU_DIALOGUE_LIST","PAUSE_MENU_FEED","PAUSE_MENU_FREEMODE_MAP","PAUSE_MENU_FRIENDS_STATS_SP","PAUSE_MENU_GALLERY","PAUSE_MENU_HAIR_COLOUR_LIST","PAUSE_MENU_HERITAGE_CARD","PAUSE_MENU_MAP","PAUSE_MENU_MISSION_HELP_LIST","PAUSE_MENU_MISSION_REPLAY_CARD","PAUSE_MENU_NEWSWIRE","PAUSE_MENU_PAGES_AWARDS","PAUSE_MENU_PAGES_CHAR_MOM_DAD","PAUSE_MENU_PAGES_CHAR_SELECT","PAUSE_MENU_PAGES_CORONA","PAUSE_MENU_PAGES_CORONA_LOBBY","PAUSE_MENU_PAGES_CORONA_PLAYERS","PAUSE_MENU_PAGES_CORONA_RACE","PAUSE_MENU_PAGES_CREWS","PAUSE_MENU_PAGES_FRIENDS","PAUSE_MENU_PAGES_FRIENDS_MP","PAUSE_MENU_PAGES_GALLERY","PAUSE_MENU_PAGES_GAME","PAUSE_MENU_PAGES_INFO","PAUSE_MENU_PAGES_MAP","PAUSE_MENU_PAGES_MISSIONCREATOR","PAUSE_MENU_PAGES_SAVE","PAUSE_MENU_PAGES_STATS","PAUSE_MENU_PAGES_STORE","PAUSE_MENU_PAGES_WEAPONS","PAUSE_MENU_REPLAY_LIST","PAUSE_MENU_SPCHAR_OVERLAYS","PAUSE_MENU_STATS_LIST","PAUSE_MENU_STATS_VERTICAL_LIST","PAUSE_MENU_STORE_NEWS","PAUSE_MENU_TEXT_LIST_FULL","PAUSE_MENU_WEAPONS","PAUSE_MP_MENU_PLAYER_COMPARISON_CARD","PLAYBACK_PANEL","PLAYER_NAME","PLAYER_SWITCH","PLAYER_SWITCH_STATS_PANEL","PLAYHEAD_MARKER","POWER_PLAY","POWER_PLAY_BIKER","POWER_PLAY_DAY_NIGHT","POWER_PLAY_GENERIC","POWER_PLAY_SPECIAL_RACES","POWER_PLAY_TURF","POWER_PLAY_VEHICLE","PSYCHOLOGY_REPORT","RACE_MESSAGE","RACE_POSITION","RAMPAGE","REMOTE_SNIPER_HUD","REMOTE_SNIPER_LOADING","ROUND_DECIMAL_PLACES","SAVING_FOOTER","SCORE_CLIP","SECURITY_CAM","SECURITY_CAMERA","SECUROSERV","SETTINGS","SHOP_MENU","SHOP_MENU_DLC","SHUTTER","SLOT_MACHINE","SOCIAL_CLUB_TV","SP_PLAYER_CARD","SP_PLAYER_COMPARISON_CARD","SPEED_INDICATOR","SPLASH_TEXT","SPPED_INDICATOR","STAGE","STAGE_CLIP","STARTER_PACK_BROWSER","STORE_BACKGROUND","STORE_BLACKOUT","STORE_CONTENTIMAGE_LIST","STORE_DETAILS_LIST","STORE_VERTICAL_LIST","STRENGTH_TEST_SCORE","STUNT_JUMPS","SUB_CAM","SUB_PC","TATTOO_BUTTONS","TAXI_DISPLAY","TEETH_PULLING","TEXT_CANVAS","TEXT_CLIP","TEXT_INPUT_BOX","TEXT_MESSAGE_LIST","TEXT_MESSAGE_VIEW","TEXTFIELD","THUMBNAIL_CLIP","TIMECODE_MC","TIMECODE_NEW","TIMELINE_PANEL","TRAFFIC_CAM","TURRET_CAM","TV_FRAME","VAULT_DRILL","VAULT_LASER","VIDEO_BUTTON_TYPES","VIDEO_CLIP","WAREHOUSE","WATERMARK","WIND_METER","XYZ","YACHT_NAME","YACHT_NAME_STERN","YOGA_BUTTONS"};
	const std::string generic2[3]		= { "DIGITAL_SAFE_DISPLAY", "ISLAND_HEIST_BOARD", "SUBMARINE_MISSILES" };
	const std::string heist_mp[6]		= { "HACKING_MESSAGE", "HEIST_CELEBRATION", "HEIST_MP", "HEIST_PRE", "HEISTMAP_MP", "INTERIORS" };
	const std::string minigames[12]		= { "AXE_OF_FURY","DANCER","DARTS_SCOREBOARD","DARTS_SCOREBOARD_BIKER","DONT_CROSS_THE_LINE","GOLF","GOLF_FLOATING_UI","HORSE_RACING_CONSOLE","HORSE_RACING_WALL","SC_LEADERBOARD","SPIN_THE_WHEEL","TENNIS" };
	const std::string minimap[11]		= {"FOG_MC","GOLF_COURSE","GREEN_AND_FRIENDLY","GREEN_AND_NET_PLAYER1","GREEN_AND_NET_PLAYER2","GREEN_AND_NET_PLAYER3","MINIMAP","MINIMAP_MAIN_MAP","NET_PLAYER1_AND_NET_PLAYER2","NET_PLAYER1_AND_NET_PLAYER3","TXD_MC"};
	//Private because the user can implement their own draw function if they need it. ffs. (Mainly because of Heist Celebration needing access to the BG and FG layers).
	void Draw();
};